In [2]:


import matplotlib.pyplot as plt


from sklearn.datasets import fetch_lfw_people

from sklearn.model_selection import RandomizedSearchCV, train_test_split
from sklearn.preprocessing import StandardScaler


In [3]:
lfw_people = fetch_lfw_people(min_faces_per_person=70, resize=0.4)

n_samples, h, w = lfw_people.images.shape


X = lfw_people.data
n_features = X.shape[1]


y = lfw_people.target
target_names = lfw_people.target_names
n_classes = target_names.shape[0]

print("Total dataset size:")
print("n_samples: %d" % n_samples)
print("n_features: %d" % n_features)
print("n_classes: %d" % n_classes)

Total dataset size:
n_samples: 1288
n_features: 1850
n_classes: 7


In [4]:
for i in range(5):  # Print 5 samples
    print("Sample", i+1)
    print("Image:", lfw_people.images[i])
    print("Target:", lfw_people.target[i], "(Person:", target_names[lfw_people.target[i]], ")")
    print()

Sample 1
Image: [[0.9973857  0.99607843 0.9921568  ... 0.29803923 0.24836601 0.20653595]
 [0.9973857  0.9921569  0.9908497  ... 0.30588236 0.2535948  0.21568628]
 [0.96078426 0.93071896 0.8679738  ... 0.2875817  0.24183007 0.21568628]
 ...
 [0.34509805 0.26143792 0.17385621 ... 0.4248366  0.40261438 0.39084968]
 [0.30980393 0.23398693 0.17124183 ... 0.39869282 0.4013072  0.3764706 ]
 [0.28366014 0.2248366  0.18039216 ... 0.38169935 0.38823533 0.3803922 ]]
Target: 5 (Person: Hugo Chavez )

Sample 2
Image: [[0.14771242 0.19738562 0.1751634  ... 0.24183007 0.2        0.14509805]
 [0.18039216 0.24836601 0.24575163 ... 0.21437909 0.21960784 0.1751634 ]
 [0.21045752 0.303268   0.33594772 ... 0.2653595  0.18431373 0.16993465]
 ...
 [0.2875817  0.29803923 0.29673204 ... 0.503268   0.46797386 0.4535948 ]
 [0.29411766 0.29803923 0.303268   ... 0.4928105  0.4496732  0.45359477]
 [0.30457518 0.29673204 0.29673204 ... 0.45751634 0.44444445 0.53594774]]
Target: 6 (Person: Tony Blair )

Sample 3
Imag

In [5]:
import numpy as np


class_distribution = np.bincount(y)
class_labels = [target_names[i] for i in range(n_classes)]

pixel_mean = np.mean(X, axis=0)
pixel_std = np.std(X, axis=0)


print("\nClass Distribution:")
print("===================")
for label, count in zip(class_labels, class_distribution):
    print(f"Class: {label}, Count: {count}")


print("\nPixel Value Statistics:")
print("========================")
print("Mean Pixel Value:")
print(pixel_mean)
print("\nStandard Deviation of Pixel Value:")
print(pixel_std)



Class Distribution:
Class: Ariel Sharon, Count: 77
Class: Colin Powell, Count: 236
Class: Donald Rumsfeld, Count: 121
Class: George W Bush, Count: 530
Class: Gerhard Schroeder, Count: 109
Class: Hugo Chavez, Count: 71
Class: Tony Blair, Count: 144

Pixel Value Statistics:
Mean Pixel Value:
[0.3557689  0.3746254  0.41296542 ... 0.4654134  0.43685618 0.40432248]

Standard Deviation of Pixel Value:
[0.18006772 0.17449939 0.1691379  ... 0.30331162 0.3022159  0.30313924]


In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Preprocessing the features (pixel values)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [9]:
!pip install scikit-learn
import sklearn

label_encoder = sklearn.preprocessing.LabelEncoder()
y_train = label_encoder.fit_transform(y_train)
y_test = label_encoder.transform(y_test)

In [13]:
y_train = to_categorical(y_train, num_classes=n_classes)
y_test = to_categorical(y_test, num_classes=n_classes)

In [11]:
!pip install keras

In [12]:
from keras.utils import to_categorical

In [15]:
from tensorflow import keras

In [17]:
from keras import layers
model = keras.Sequential([
    layers.Dense(512, activation='relu', input_shape=(n_features,)),
    layers.Dropout(0.5),
    layers.Dense(n_classes, activation='softmax')
])

In [18]:
print(layers)

<module 'keras.layers' from '/usr/local/lib/python3.10/dist-packages/keras/layers/__init__.py'>


In [19]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [20]:
model.fit(X_train, y_train, epochs=20, batch_size=32, validation_split=0.2)

Epoch 1/20
26/26 [==============================] - 2s 34ms/step - loss: 2.2503 - accuracy: 0.4660 - val_loss: 1.4943 - val_accuracy: 0.6408
Epoch 2/20
26/26 [==============================] - 1s 22ms/step - loss: 1.0841 - accuracy: 0.7451 - val_loss: 1.5651 - val_accuracy: 0.7087
Epoch 3/20
26/26 [==============================] - 1s 23ms/step - loss: 0.9620 - accuracy: 0.7961 - val_loss: 1.3870 - val_accuracy: 0.6990
Epoch 4/20
26/26 [==============================] - 1s 22ms/step - loss: 0.6756 - accuracy: 0.8398 - val_loss: 1.3190 - val_accuracy: 0.6990
Epoch 5/20
26/26 [==============================] - 0s 16ms/step - loss: 0.5305 - accuracy: 0.8665 - val_loss: 1.2242 - val_accuracy: 0.7330
Epoch 6/20
26/26 [==============================] - 0s 14ms/step - loss: 0.4069 - accuracy: 0.8871 - val_loss: 1.3194 - val_accuracy: 0.7476
Epoch 7/20
26/26 [==============================] - 0s 16ms/step - loss: 0.3584 - accuracy: 0.9114 - val_loss: 1.5166 - val_accuracy: 0.7427
Epoch 8/20
26

In [21]:
test_loss, test_acc = model.evaluate(X_test, y_test)
print('Test accuracy:', test_acc)

9/9 [==============================] - 0s 4ms/step - loss: 1.2522 - accuracy: 0.8256
Test accuracy: 0.8255813717842102


In [25]:
from sklearn.metrics import precision_score, recall_score, f1_score

# Step 4 (continued): Model Evaluation
test_loss, test_acc = model.evaluate(X_test, y_test)
print('Test accuracy:', test_acc)

# Additional evaluation metrics
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true = np.argmax(y_test, axis=1)

precision = precision_score(y_true, y_pred_classes, average='weighted')
recall = recall_score(y_true, y_pred_classes, average='weighted')
f1 = f1_score(y_true, y_pred_classes, average='weighted')

print('Precision:', precision)
print('Recall:', recall)
print('F1-score:', f1)

9/9 [==============================] - 0s 11ms/step - loss: 1.2522 - accuracy: 0.8256
Test accuracy: 0.8255813717842102
9/9 [==============================] - 0s 11ms/step
Precision: 0.8340098759025907
Recall: 0.8255813953488372
F1-score: 0.8232699616378913


In [23]:
import tensorflow as tf

In [24]:
model_path = "gender_detection_model"
tf.saved_model.save(model, model_path)